include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    lines_longer_than_80_chars: true
    sort_pub_dependencies: false
    constant_identifier_names: true
    prefer_single_quotes: true
