include: package:lint/strict.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    lines_longer_than_80_chars: true
    always_specify_types: true
    sort_pub_dependencies: false
